# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: States Manager
version: "1.0.0"
slug: states-manager
description: States Manager
url: "https://github.com/Dehil/states_manager
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"